const sampleDataSet = [
  {
    name: "ABC GYM, NYC",
    date: "2023-08-26",
    time: "10:00 AM",
    duration: "1 hour",
    status: "Active",
  },
  {
    name: "FitZone Fitness",
    date: "2023-08-27",
    time: "11:30 AM",
    duration: "45 minutes",
    status: "Active",
  },
  {
    name: "HealthyLife Gym",
    date: "2023-08-27",
    time: "3:00 PM",
    duration: "2 hours",
    status: "Active",
  },
  {
    name: "Flex Fitness Center",
    date: "2023-09-02",
    time: "9:30 AM",
    duration: "1.5 hours",
    status: "Active",
  },
  {
    name: "Strength Zone Gym",
    date: "2023-09-02",
    time: "5:45 PM",
    duration: "1 hour",
    status: "Active",
  },
  {
    name: "Energize Fitness Studio",
    date: "2023-09-03",
    time: "12:00 PM",
    duration: "1.25 hours",
    status: "Active",
  },
  {
    name: "ABC GYM, NYC",
    date: "2023-08-26",
    time: "10:00 AM",
    duration: "1 hour",
    status: "Active",
  },
  {
    name: "FitZone Fitness",
    date: "2023-08-27",
    time: "11:30 AM",
    duration: "45 minutes",
    status: "Active",
  },
  {
    name: "HealthyLife Gym",
    date: "2023-08-28",
    time: "3:00 PM",
    duration: "2 hours",
    status: "Active",
  },
  {
    name: "StrongBody Fitness Center",
    date: "2023-08-29",
    time: "9:30 AM",
    duration: "1.5 hours",
    status: "Active",
  },
  {
    name: "PowerLift Gym",
    date: "2023-08-30",
    time: "5:45 PM",
    duration: "1 hour",
    status: "Active",
  },
  {
    name: "Energize Fitness Studio",
    date: "2023-08-31",
    time: "12:00 PM",
    duration: "1.25 hours",
    status: "Active",
  },
  {
    name: "TotalFit Gym",
    date: "2023-09-01",
    time: "9:00 AM",
    duration: "1.5 hours",
    status: "Active",
  },
  {
    name: "BodyPulse Fitness",
    date: "2023-09-02",
    time: "2:30 PM",
    duration: "2 hours",
    status: "Active",
  },
  {
    name: "Wellness Hub",
    date: "2023-09-03",
    time: "11:00 AM",
    duration: "1 hour",
    status: "Active",
  },
  {
    name: "FlexFit Studio",
    date: "2023-09-04",
    time: "4:45 PM",
    duration: "1.5 hours",
    status: "Active",
  },
  {
    name: "BodyRevive Gym",
    date: "2023-09-05",
    time: "10:30 AM",
    duration: "1.25 hours",
    status: "Active",
  },
  {
    name: "ShapeUp Fitness",
    date: "2023-09-06",
    time: "3:15 PM",
    duration: "1.5 hours",
    status: "Active",
  },
  {
    name: "PureStrength Gym",
    date: "2023-09-07",
    time: "1:00 PM",
    duration: "1 hour",
    status: "Active",
  },
  {
    name: "WellFit Club",
    date: "2023-09-08",
    time: "5:30 PM",
    duration: "2 hours",
    status: "Active",
  },
  {
    name: "BodyBalance Studio",
    date: "2023-09-09",
    time: "9:45 AM",
    duration: "1.25 hours",
    status: "Active",
  },
  {
    name: "ActiveLife Fitness",
    date: "2023-09-10",
    time: "3:30 PM",
    duration: "1.5 hours",
    status: "Active",
  },
  {
    name: "GymHub Center",
    date: "2023-09-11",
    time: "12:15 PM",
    duration: "1 hour",
    status: "Active",
  },
  {
    name: "CoreStrength Gym",
    date: "2023-09-12",
    time: "6:00 PM",
    duration: "1.5 hours",
    status: "Active",
  },
  {
    name: "HealthFusion Fitness",
    date: "2023-09-13",
    time: "11:30 AM",
    duration: "1 hour",
    status: "Active",
  },
  {
    name: "Vitality Studio",
    date: "2023-09-14",
    time: "4:45 PM",
    duration: "1.25 hours",
    status: "Active",
  },
  {
    name: "Elevate Gym",
    date: "2023-09-15",
    time: "10:00 AM",
    duration: "1.5 hours",
    status: "Active",
  },
];

export default sampleDataSet;
